name: flutter_app_template
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  # Authentication
  oauth2: ^2.0.0

  # Dependency injection
  get_it: ^6.1.1
  provider: ^5.0.0

  # Functional programming
  dartz: ^0.10.0-nullsafety.2

  # GraphQL client
  graphql: ^5.0.0

  # HTTP client
  dio: ^4.0.0

  # Immutable elements
  freezed_annotation: ^0.14.2
  kt_dart: ^0.9.1

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Logging
  emoji_lumberdash: ^2.0.0
  lumberdash: ^3.0.0

  # Routing/Navigation
  auto_route: ^2.2.0

  # State management
  flutter_bloc: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: any

  # Immutable elements
  freezed: any

  # Linting
  lint: any

  # Routing/Navigation
  auto_route_generator: any

  # Serialization
  json_serializable: ^4.1.1

  # Testing
  bloc_test: ^8.0.2
  mocktail: ^0.1.4

flutter:
  uses-material-design: true

  # Flutter generation
  generate: true

  assets:
    - assets/app_icon/
