name: Testing

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "android/**"
      - "ios/**"
      - "lib/**"
      - "test/**"
      - "web/**"
      - "analysis_options.yaml"
      - "pubspec.yaml"
  push:
    paths:
      - ".github/workflows/**"
      - "android/**"
      - "ios/**"
      - "lib/**"
      - "web/**"
      - "test/**"
      - "analysis_options.yaml"
      - "pubspec.yaml"

jobs:
  app-test:
    name: Format, analyze and test the app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Java actions
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter actions
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Format Dart files within `lib` and `test` folders and abort on formatting changes
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze Dart files within `lib` and `test` considering infos and warnings
        run: mkdir -p assets/config && flutter analyze --no-pub --fatal-infos --fatal-warnings

      - name: Run tests
        run: flutter test --coverage --no-pub --test-randomize-ordering-seed random

      - name: CHeck 100% code coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          exclude: "**/*.freezed.dart **/*.g.dart **/*.gr.dart"
