name: Testing

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "android/**"
      - "ios/**"
      - "lib/**"
      - "test/**"
      - "web/**"
      - "analysis_options.yaml"
      - "pubspec.yaml"
  push:
    paths:
      - ".github/workflows/**"
      - "android/**"
      - "ios/**"
      - "lib/**"
      - "web/**"
      - "test/**"
      - "analysis_options.yaml"
      - "pubspec.yaml"

jobs:
  setup:
    name: Format, analyze and ensure up-to-date code generation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2

      - name: Setup Java actions
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter actions
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Format Dart files within `lib` and `test` folders and abort on formatting changes
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze Dart files considering infos and warnings as failures
        run: flutter analyze --no-pub --fatal-infos --fatal-warnings

      - name: Ensure up-to-date code generation
        run: flutter pub run test --run-skipped -t ci-only test/up_to_date_code_gen_test.dart

  build:
    name: Test app implementation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v2

      - name: Setup Java actions
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter actions
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests adn generate coverage
        run: flutter test --coverage --no-pub -x ci-only -r expanded --test-randomize-ordering-seed random

      - name: Check 100% code coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          exclude: "**/*.freezed.dart **/*.g.dart **/*.gr.dart"
